on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: requirements-dev.txt
      - run: pip install -U --upgrade-strategy eager -r requirements-dev.txt
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.IAM_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.IAM_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
      - run: chalice deploy --stage prod
